"""
The load pass: source rows in, Oracle rows out, ids preserved.

Ordering is the whole design. Tables go in FK-safe order (spec.PLAN's
`order`), self-referencing columns are patched after their table is full,
and audit_logs is written in one ascending-id pass so V28's trigger rebuilds
the same hash chain the source carries.

Identity columns are switched to GENERATED BY DEFAULT for the load and
switched back with START WITH LIMIT VALUE afterwards, so the first row the
application writes post-cutover starts above every migrated id.
"""
from __future__ import annotations

import os
import re
import time
from dataclasses import dataclass, field
from typing import Iterator

from . import transforms
from .db import BATCH
from .spec import TableSpec

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
V36_1_PATH = os.path.join(
    _REPO_ROOT,
    "java-backend",
    "src",
    "main",
    "resources",
    "db",
    "migration",
    "V36_1__legacy_permission_override_backfill.sql",
)


@dataclass
class TableResult:
    target: str
    rows_read: int = 0
    rows_written: int = 0
    self_fk_patched: int = 0
    seconds: float = 0.0
    postload: list[str] = field(default_factory=list)
    skipped_reason: str | None = None


@dataclass
class LoadResult:
    tables: list[TableResult] = field(default_factory=list)
    global_steps: list[str] = field(default_factory=list)
    dry_run: bool = False

    @property
    def rows_written(self) -> int:
        return sum(t.rows_written for t in self.tables)


def transform_row(spec: TableSpec, row: tuple) -> tuple:
    """Map one source row onto the target column order.

    Self-FK columns are excluded here (they are patched later), so the tuple
    lines up with spec.insert_columns.
    """
    by_source = dict(zip(spec.source_columns, row))
    return tuple(
        transforms.apply(col.transform, by_source[col.source]) for col in spec.insert_columns
    )


def _batches(rows: Iterator[tuple], size: int) -> Iterator[list[tuple]]:
    batch: list[tuple] = []
    for row in rows:
        batch.append(row)
        if len(batch) >= size:
            yield batch
            batch = []
    if batch:
        yield batch


def load_table(source, target, spec: TableSpec, *, dry_run: bool, batch: int = BATCH) -> TableResult:
    result = TableResult(target=spec.target)
    started = time.monotonic()
    insert_cols = [c.target for c in spec.insert_columns]
    lobs = {c.target: c.lob for c in spec.insert_columns if c.lob}

    if spec.identity and not dry_run:
        target.identity_allow_explicit(spec.target)

    source_rows = source.stream(spec.source, spec.source_columns, spec.extract_order, batch)
    for chunk in _batches((transform_row(spec, r) for r in source_rows), batch):
        result.rows_read += len(chunk)
        if not dry_run:
            target.insert_many(spec.target, insert_cols, lobs, chunk)
            result.rows_written += len(chunk)

    # Self-FKs: the parent row may sit anywhere in the table, so the column is
    # inserted NULL and set once every row exists.
    if spec.self_fk_columns:
        cols = [c.source for c in spec.self_fk_columns]
        targets = [c.target for c in spec.self_fk_columns]
        pending: list[tuple] = []
        for row in source.stream(spec.source, [*cols, *spec.pk], spec.extract_order, batch):
            if any(v is not None for v in row[: len(cols)]):
                pending.append(row)
        result.self_fk_patched = len(pending)
        if not dry_run:
            for chunk in _batches(iter(pending), batch):
                target.update_many(spec.target, targets, spec.pk, chunk)

    if not dry_run:
        # Post-load statements are Oracle SQL, taken from the migrations they
        # re-run (V35/V42). The rehearsal target cannot execute them, and
        # translating them into a second dialect would mean rehearsing
        # something other than what production runs.
        oracle_target = getattr(target, "kind", "") == "oracle"
        for sql in spec.postload_sql:
            if oracle_target:
                target.execute(sql.strip())
                result.postload.append(_summarise(sql))
            else:
                result.postload.append(f"skipped (not an Oracle target): {_summarise(sql)}")
        target.commit()
        if spec.identity:
            target.identity_restore(spec.target)

    result.seconds = round(time.monotonic() - started, 3)
    return result


def _summarise(sql: str) -> str:
    return " ".join(sql.split())[:120]


def read_v36_1_backfill() -> str:
    """The permission-override MERGE, read from the migration itself.

    Deliberately not a copy: V36_1 is the approved statement, and a second
    hand-maintained version of it here would be one refactor away from
    disagreeing with the migration it is meant to reproduce.
    """
    with open(V36_1_PATH, encoding="utf-8") as handle:
        sql = handle.read()
    sql = re.sub(r"^\s*--.*$", "", sql, flags=re.MULTILINE)
    return sql.strip().rstrip(";").strip()


def post_load_global(target, *, dry_run: bool) -> list[str]:
    """Steps that need the whole database loaded, not one table.

    V36_1 is the load-bearing one. It converts each user's legacy
    `permissions` JSON into explicit ALLOW/DENY overrides -- but Flyway ran
    it against an empty users table long before this data existed, so
    without re-running it here every migrated user would silently fall back
    to their role's default permissions, quietly widening or narrowing
    access for anyone who had a manual grant. The statement's MERGE ... WHEN
    NOT MATCHED makes the second run safe.
    """
    steps: list[str] = []
    if getattr(target, "kind", "") != "oracle":
        steps.append("V36_1 permission-override backfill: skipped (not an Oracle target)")
        return steps
    if dry_run:
        steps.append("V36_1 permission-override backfill: would re-run (dry run)")
        return steps
    target.execute(read_v36_1_backfill())
    target.commit()
    count = target.scalar("SELECT COUNT(*) FROM user_permission_overrides")
    steps.append(f"V36_1 permission-override backfill re-run: {count} override row(s) present")
    return steps


def run(source, target, specs: list[TableSpec], *, dry_run: bool = False, batch: int = BATCH) -> LoadResult:
    result = LoadResult(dry_run=dry_run)
    for spec in specs:
        result.tables.append(load_table(source, target, spec, dry_run=dry_run, batch=batch))
    result.global_steps.extend(post_load_global(target, dry_run=dry_run))
    return result
