WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO OFF FEEDBACK ON HEADING OFF PAGESIZE 0

DECLARE
    user_missing EXCEPTION;
    PRAGMA EXCEPTION_INIT(user_missing, -1918);
BEGIN
    EXECUTE IMMEDIATE 'DROP USER MAGTI_QA CASCADE';
EXCEPTION
    WHEN user_missing THEN NULL;
END;
/

EXIT SUCCESS
