package ge.magti.portal.org;

import ge.magti.portal.domain.AssignmentType;
import ge.magti.portal.domain.Department;
import ge.magti.portal.domain.LeadershipAssignment;
import ge.magti.portal.domain.Team;
import ge.magti.portal.domain.User;
import ge.magti.portal.repository.DepartmentRepository;
import ge.magti.portal.repository.LeadershipAssignmentRepository;
import ge.magti.portal.repository.TeamRepository;
import ge.magti.portal.repository.UserRepository;
import ge.magti.portal.util.TbilisiTime;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Runs the Phase 2 transitional backfill, or reports what it would do.
 *
 * <p>{@link #plan()} and {@link #apply(Long)} share one
 * {@link OrgBackfillPlanner} call, so the dry run cannot describe something
 * other than what applying it does. That is the entire reason the planner is a
 * separate pure function: a report generated by different code from the writer
 * is a report of a different program.
 *
 * <p><b>Idempotent.</b> Re-running creates no duplicate group, moves nobody
 * twice and adds no second assignment. The plan requires this because the
 * backfill has to be safe to run repeatedly against production while the
 * reconciliation list is being worked through -- V37 cannot apply until that
 * list is empty, and getting there takes more than one pass.
 *
 * <p><b>Nothing calls this yet.</b> There is deliberately no endpoint: the
 * backfill is an operator action with a reconciliation report attached, not a
 * button, and the decision about how it is triggered belongs with the
 * system-admin UI in Phase 8.
 */
@Service
public class OrgBackfillService {

    private final UserRepository userRepository;
    private final DepartmentRepository departmentRepository;
    private final TeamRepository teamRepository;
    private final LeadershipAssignmentRepository leadershipAssignmentRepository;

    public OrgBackfillService(
            UserRepository userRepository, DepartmentRepository departmentRepository,
            TeamRepository teamRepository, LeadershipAssignmentRepository leadershipAssignmentRepository) {
        this.userRepository = userRepository;
        this.departmentRepository = departmentRepository;
        this.teamRepository = teamRepository;
        this.leadershipAssignmentRepository = leadershipAssignmentRepository;
    }

    /** What the backfill would do. Writes nothing. */
    public OrgBackfillPlan plan() {
        return OrgBackfillPlanner.plan(
                userRepository.findByActiveTrue(),
                departmentRepository.findAll(),
                teamRepository.findAll());
    }

    /**
     * Applies the plan and returns it, so the caller can render the same
     * reconciliation report afterwards.
     *
     * @param actorId the system admin running it, recorded on every assignment
     *                this creates -- a backfilled leader must be traceable to
     *                the person who ran the backfill, not appear from nowhere
     */
    @Transactional
    public OrgBackfillPlan apply(Long actorId) {
        OrgBackfillPlan plan = plan();

        Map<String, Long> teamIdByKey = new LinkedHashMap<>();
        for (Team team : teamRepository.findAll()) {
            if (team.getDepartmentId() != null) {
                teamIdByKey.put(key(team.getDepartmentId(), team.getName()), team.getId());
            }
        }

        for (OrgBackfillPlan.TeamToCreate toCreate : plan.teamsToCreate()) {
            String teamKey = key(toCreate.departmentId(), toCreate.name());
            if (teamIdByKey.containsKey(teamKey)) {
                continue;
            }
            Team team = new Team();
            team.setName(toCreate.name());
            team.setDepartmentId(toCreate.departmentId());
            team.setCreatedAt(TbilisiTime.now());
            team.setActive(true);
            // No ad_external_id: this group was inferred from a free-text
            // string, not received from AD. A null there is what tells the
            // later reconciliation which groups AD has never confirmed.
            teamIdByKey.put(teamKey, teamRepository.saveAndFlush(team).getId());
        }

        Map<Long, User> usersById = new LinkedHashMap<>();
        for (User user : userRepository.findByActiveTrue()) {
            usersById.put(user.getId(), user);
        }

        for (OrgBackfillPlan.Membership membership : plan.memberships()) {
            Long teamId = teamIdByKey.get(key(membership.departmentId(), membership.groupName()));
            User user = usersById.get(membership.userId());
            if (user == null || teamId == null || teamId.equals(user.getTeamId())) {
                continue;
            }
            // users.department is deliberately untouched -- see
            // OrgBackfillPlanner's "format-preserving" note.
            user.setTeamId(teamId);
            userRepository.save(user);
        }

        for (OrgBackfillPlan.LeadershipCandidate candidate : plan.leadership()) {
            Long teamId = teamIdByKey.get(key(candidate.departmentId(), candidate.groupName()));
            if (teamId == null) {
                continue;
            }
            boolean alreadyLeads = leadershipAssignmentRepository
                    .findByUserIdAndActiveTrue(candidate.userId()).stream()
                    .anyMatch(existing -> teamId.equals(existing.getTeamId()));
            if (alreadyLeads) {
                continue;
            }
            LeadershipAssignment assignment = new LeadershipAssignment();
            assignment.setUserId(candidate.userId());
            assignment.setTeamId(teamId);
            assignment.setAssignmentType(AssignmentType.PRIMARY);
            assignment.setActive(true);
            assignment.setStartedAt(TbilisiTime.now());
            assignment.setCreatedBy(actorId);
            assignment.setSource(LeadershipAssignment.Source.BACKFILL);
            leadershipAssignmentRepository.save(assignment);
        }

        return plan;
    }

    /**
     * The reconciliation report, grouped by what went wrong rather than by
     * user, because it is worked through one category at a time: every
     * unmapped department is usually one typo, and every duplicate primary is
     * one conversation.
     */
    public static String report(OrgBackfillPlan plan) {
        StringBuilder text = new StringBuilder();
        text.append("Org backfill reconciliation\n");
        text.append("  groups to create : ").append(plan.teamsToCreate().size()).append('\n');
        text.append("  memberships      : ").append(plan.memberships().size()).append('\n');
        text.append("  leaders resolved : ").append(plan.leadership().size()).append('\n');
        text.append("  needs a decision : ").append(plan.issues().size()).append('\n');

        Map<OrgBackfillIssue.Kind, List<OrgBackfillIssue>> byKind = new TreeMap<>();
        for (OrgBackfillIssue issue : plan.issues()) {
            byKind.computeIfAbsent(issue.kind(), k -> new java.util.ArrayList<>()).add(issue);
        }
        for (Map.Entry<OrgBackfillIssue.Kind, List<OrgBackfillIssue>> entry : byKind.entrySet()) {
            text.append('\n').append(entry.getKey()).append(" (").append(entry.getValue().size()).append(")\n");
            for (OrgBackfillIssue issue : entry.getValue()) {
                text.append("  - ");
                if (issue.userId() != null) {
                    text.append("user ").append(issue.userId()).append(": ");
                }
                text.append(issue.detail());
                if (issue.subject() != null) {
                    text.append(" [").append(issue.subject()).append(']');
                }
                text.append('\n');
            }
        }

        if (!plan.hasUnresolvedIssues()) {
            text.append("\nNothing outstanding: V37 may be applied.\n");
        } else {
            text.append("\nV37 must NOT be applied while any of the above is unresolved.\n");
        }
        return text.toString();
    }

    private static String key(Long departmentId, String name) {
        return departmentId + " " + name;
    }
}
